spring:
  application:
    name: spring-cloud-api-gateway-service
#  cloud:
#    gateway:
#       routes:
#         - id: stock-enquiry
#           uri: 
#              lb://product-enquiry-service
#           predicates:
#             - Path=/product/**
    
server:
  port: ${port:8900}
  
  