spring:
  application:
    name: spring-cloud-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Geon-Kuncherichen/environment-variable-repo.git
          
          default-label: main

server:
  port: ${port:8888}